blog.py::RSSPage use doc.HTMLPage instead of model.BasePage resolves cubictemp name space errors
    cubicTemp.TemplateError: NameError: "name 'myfunction' is not definied"

where myfunction is defined and put into the namespace in my site index.py but not recognised when
generating RSS pages.